{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suduko.serviceAccountName" . }}
  labels:
{{ include "suduko.labels" . | indent 4 }}
{{- end -}}
